### ISSUE TITLE
Profile engine

### ISSUE THREAD

**Issue by lidavidm** [HaliteChallenge/Halite-III#120]
`HaliteImpl::update_inspiration` might be slow (with lots of ships?) (thanks to AlanTuring on the forums)

**Comment by AdamStelmaszczyk** [comment]
Simple for-loop in the inspiration area might be faster than maintaining two sets (https://github.com/HaliteChallenge/Halite-III/blob/master/game_engine/core/HaliteImpl.cpp#L415). But profiling will be needed anyway (also to confirm that `update_inspiration` is the bottleneck).

**Comment by lidavidm** [comment]
I did a `perf` run and generated a flamegraph on Linux, using a game with a few hundred ships. `update_inspiration` is responsible for about 5% of the total 16 second runtime. (The Python script I was using to replay bot output took far more CPU time.) While 0.8 seconds is not trivial, it is also not an enormous amount of time compared to everything else.
