### ISSUE TITLE
engine error

### ISSUE THREAD

**Issue by samamiller** [HaliteChallenge/Halite-III#124]
My script runs fine with 1 player but with more players the engine claims it can't open the file.
![capture1](https://user-images.githubusercontent.com/37316265/47810011-e4ec4880-dd07-11e8-9793-a43408ba5bcc.PNG)
![capture2](https://user-images.githubusercontent.com/37316265/47810016-e6b60c00-dd07-11e8-8bd7-884bd045c142.PNG)

Here is a 1 player run
![capture3](https://user-images.githubusercontent.com/37316265/47810027-efa6dd80-dd07-11e8-8ba8-3d7bce269754.PNG)

**Comment by samamiller** [comment]
@snaar do you have the old prebuilt versions of the game engine? I would like to check this on the launch version of the engine.  I updated my engines to 1.0.2.171.g677d7 and didn't save the old versions.

**Comment by snaar** [comment]
That's not engine erroring, this is engine echoing what it received on stdin from whatever your bot was executing. So the error is not in the engine, error is in whatever it's trying to run. How does run_game.sh look for you?

**Comment by snaar** [comment]
We don't really keep old engine versions around, sorry.

**Comment by samamiller** [comment]
run_game.sh is boiler plate
#!/bin/sh

./halite --replay-directory replays/ -vvv --width 32 --height 32 "julia --project MyBot.jl" "julia --project MyBot.jl"

How can that be a bot error if it executes fine with 1 player? Even in the 2 player version player 0 is initialized successfully while player 1 fails with the same exact file.

**Comment by snaar** [comment]
Can you try running "julia --project MyBot.jl" from two separate terminals at the same time? I wonder if it's some kind of Julia issue.

**Comment by samamiller** [comment]
Running 2 instances of a 1 player in seperate terminals at the same time works just fine.

**Comment by snaar** [comment]
I guess we'll have to try to reproduce this locally.

**Comment by samamiller** [comment]
What is set_version.sh doing I keep getting 
: not foundon.sh: 2: ./set_version.sh:
./set_version.sh: 2: ./set_version.sh: Syntax error: "|" unexpected

**Comment by samamiller** [comment]
Well, I found the error.  It wasn't a engine error but a line ending error `dos2unix run_game.sh` fixed it. I develop on windows and it seems like vs code changed my line endings somehow even though I have my gitconfig setup for it not to.  I'll just have to remember to add dos2unix to my workflow.

**Comment by snaar** [comment]
Ah good. Glad you found it!
