### ISSUE TITLE
julia broken

### ISSUE THREAD

**Issue by samamiller** [HaliteChallenge/Halite-III#128]
Can someone with access to the server tell me which version of compiler.py is currently running?
If it is 2cfd355 would it be possible to hotfix -> 3672ce5?

**Comment by lidavidm** [comment]
It is still 2cfd355, yes. I can redeploy the worker blob.

**Comment by lidavidm** [comment]
@samamiller give it another try!

**Comment by samamiller** [comment]
Thanks @lidavidm, it looks like it's working again.  My install.sh bot works fine, however, the random starter bot I made still doesn't compile right for some reason.

**Comment by lidavidm** [comment]
let me poke it and see...

**Comment by lidavidm** [comment]
Turns out Julia wants to be able to create directories, and that was denied before. I'll get a change in to allow that.

**Comment by samamiller** [comment]
Thanks, its weird that my install.sh is literally almost the same thing but it works.  Is install.sh allowed to create directories?

**Comment by lidavidm** [comment]
They all run with the same permissions, so I'm as confused as you are. 

Go ahead and give it another try though, permissions should allow directories now...

**Comment by samamiller** [comment]
Random bot still doesn't work.
[match_1301166_user_518_errors.log](https://github.com/HaliteChallenge/Halite-III/files/2540419/match_1301166_user_518_errors.log)

**Comment by lidavidm** [comment]
Hmm, the install.sh creates the `packages` dir but the compiler script does not. Odd...

**Comment by lidavidm** [comment]
The `Pkg.activate` does seem necessary. However, running it through the install script works; running it through the compiler does not, even though they should have the same permissions.

**Comment by lidavidm** [comment]
So it was actually the `$(pwd)` call: it was getting shell-expanded too early, so Julia was trying to install into the worker directory, explaining the permissions thing. I'll push a patch...
