### ISSUE TITLE
julia starter bot, add Flux as in readme - compilation failed when uploading

### ISSUE THREAD

**Issue by Andersgee** [HaliteChallenge/Halite-III#138]
cloned julia starter bot, followed [README](https://github.com/HaliteChallenge/Halite-III/blob/16adbcc74a8ca7950284c66ce10b6ba89a431384/starter_kits/Julia/README_JULIA.md) for adding package Flux

bot failed to compile when uploading with the following message:

```
We had some trouble uploading your bot. If you cannot figure out why
this happened, please email us at halite@halite.io. We can help.

For our reference, here is the trace of the error:
Traceback (most recent call last):
  File "worker.py", line 164, in executeCompileTask
    archive.zipFolder(temp_dir, archive_path)
  File "/home/worker/Halite/apiserver/worker/archive.py", line 33, in zipFolder
    zipFile.write(os.path.join(rootPath, file))
  File "/usr/lib/python3.6/zipfile.py", line 1622, in write
    with open(filename, "rb") as src, self.open(zinfo, 'w') as dest:
PermissionError: [Errno 13] Permission denied: './compiled/v1.0/BinaryProvider/ek6VZ.ji'

```

**Comment by lidavidm** [comment]
It's an error on our side - looks like Julia doesn't make deps group-readable, so we can't include it in the zip. I'm hoping to redeploy soon; in the meantime, I can help you manually compile a bot, if you have a submission you want to make.
