### ISSUE TITLE
Error: constants: server did not send NEW_ENTITY_ENERGY_COST constant.

### ISSUE THREAD

**Issue by AllinaChan** [HaliteChallenge/Halite-III#141]
Since the map didn't contain the key. It triggered an IllegalStateException() error. How can I fix this?

        for (int i = 0; i < tokens.size(); i += 2) {
            constantsMap.put(tokens.get(i), tokens.get(i+1));
        }

        SHIP_COST = getInt(constantsMap, "NEW_ENTITY_ENERGY_COST");
        DROPOFF_COST = getInt(constantsMap, "DROPOFF_COST");
        MAX_HALITE = getInt(constantsMap, "MAX_ENERGY");
        MAX_TURNS = getInt(constantsMap, "MAX_TURNS");
        EXTRACT_RATIO = getInt(constantsMap, "EXTRACT_RATIO");
        MOVE_COST_RATIO = getInt(constantsMap, "MOVE_COST_RATIO");
        INSPIRATION_ENABLED = getBoolean(constantsMap, "INSPIRATION_ENABLED");
        INSPIRATION_RADIUS = getInt(constantsMap, "INSPIRATION_RADIUS");
        INSPIRATION_SHIP_COUNT = getInt(constantsMap, "INSPIRATION_SHIP_COUNT");
        INSPIRED_EXTRACT_RATIO = getInt(constantsMap, "INSPIRED_EXTRACT_RATIO");
        INSPIRED_BONUS_MULTIPLIER = getDouble(constantsMap, "INSPIRED_BONUS_MULTIPLIER");
        INSPIRED_MOVE_COST_RATIO = getInt(constantsMap, "INSPIRED_MOVE_COST_RATIO");
    }

    private static int getInt(final Map<String, String> map, final String key) {
        return Integer.parseInt(getString(map, key));
    }

    private static double getDouble(final Map<String, String> map, final String key) {
        return Double.parseDouble(getString(map, key));
    }

    private static boolean getBoolean(final Map<String, String> map, final String key) {
        final String stringValue = getString(map, key);
        switch (stringValue) {
            case "true": return true;
            case "false": return false;
            default:
                Log.log("Error: constants: " + key + " constant has value of '" + stringValue +
                    "' from server. Do not know how to parse that as boolean.");
                throw new IllegalStateException();
        }
    }

    private static String getString(final Map<String, String> map, final String key) {
        if (!map.containsKey(key)) {
            Log.log("Error: constants: server did not send " + key + " constant.");
            throw new IllegalStateException();
        }
        return map.get(key);
    }

**Comment by snaar** [comment]
(e.g. command line)

**Comment by AllinaChan** [comment]
I just use command prompt and typed in 
javac MyBot.java
java MyBot

**Comment by snaar** [comment]
Ah. You need to run halite executable with your bot provided as parameter. There should be run_game.sh and run_game.bat in the kit that you can use to run your bot.

The way it works is that game (halite) will run the bot for you and will communicate with it via console input and output. So if you run bot alone by itself, it will just sit there waiting for input from the game on the console, hence it will quit since it didn't receive anything that it expects.

Does this make sense?

**Comment by AllinaChan** [comment]
Oh thank you so much! I have another question: When I use java compiler I get errors that I need to fix. However when I use .bat I don't need to fix anything and it just automatically runs. How would I know if I made an error anywhere in my code. Thank you so much for your help!

**Comment by snaar** [comment]
You can still do the steps in the bat file manually. If you look inside it, it simply runs these two commands:
javac MyBot.java
halite.exe --replay-directory replays/ -vvv --width 32 --height 32 "java MyBot" "java MyBot"

So you can still keep running javac MyBot.java to see the errors.

**Comment by AllinaChan** [comment]
Thank you so much!

**Comment by snaar** [comment]
Welcome!
