### ISSUE TITLE
Install Nim, Kotlin

### ISSUE THREAD

**Issue by lidavidm** [HaliteChallenge/Halite-III#146]

**Comment by DanielVF** [comment]
Great! 

For nim, it's super important that the compiler has the `-d:release` flag set. Without it, nim compiles in super-slow mode. Without it, my bot is 24x slower! This is crazy!

Here's a sample nim compile command that will create a `MyBot` binary:

```
nim compile -d:release MyBot.nim
```

**Comment by lidavidm** [comment]
This is now implemented. Nim is compiled with the release flag. Let me know if there's something that doesn't work.
