### ISSUE TITLE
Auth support for forums

### ISSUE THREAD

**Issue by whatelsie** [HaliteChallenge/Halite-III#15]
Users are unable to login to forums.

**Comment by jangerhofer** [comment]
I signed up with my GitHub account and am similarly blocked from the forums, I suspect.  

Despite being logged in to my Halite account (and seeing my performance stats), when I click to the forum tab, I am prompted to login (in the top right corner).  When I click through to sign in with Github, I am met with a page which states "Login Error" at `https://forums.halite.io/session/sso_login?sso=...`

**Comment by whatelsie** [comment]
@jangerhofer reproduced the issue, thanks for the report!

**Comment by inoryy** [comment]
Same here. Happens on `Chrome 69.0.3497.92` (with and without any extensions) and on `Firefox 62.0.3` (completely fresh install).

**Comment by lidavidm** [comment]
This may be fixed - @inoryy and @jangerhofer could you give it another try?

**Comment by jangerhofer** [comment]
Yes, login works smoothly on my end as well!
