### ISSUE TITLE
CI fails on halite-in-a-box

### ISSUE THREAD

**Issue by tmarble** [HaliteChallenge/Halite-III#151]
I'm trying to add a Clojure Starter Kit (as part of PR# https://github.com/HaliteChallenge/Halite-III/pull/150 )

But CI is failing on halite-in-a-box (completely unrelated):
https://travis-ci.com/HaliteChallenge/Halite-III/jobs/158991000

```
+/Users/travis/build/HaliteChallenge/Halite-III/tools/halite-in-a-box/node_modules/.bin/electron-builder -m
/Users/travis/build/HaliteChallenge/Halite-III/tools/halite-in-a-box/node_modules/read-config-file/out/main.js:71
async function readConfig(configFile, request) {
      ^^^^^^^^
SyntaxError: Unexpected token function
```

This _looks_ like a typical node transitive dependency failure.. how can we fix it?

**Comment by lidavidm** [comment]
I'm probably going to disable CI for this; it increases the build time a lot and doesn't produce good artifacts in any case.

**Comment by tmarble** [comment]
@lidavidm Please let me know when I should try again.

I just did now, and I realize your change isn't in yet: https://travis-ci.com/HaliteChallenge/Halite-III/jobs/159111969

**Comment by lidavidm** [comment]
We won't reject your PR because the build fails! (It only tests the engine/a few starter kits anyways) We'll get around to reviewing when we get a chance.

**Comment by tmarble** [comment]
@lidavidm hmm.. for extra credit should I write CI tests for the Clojure starter kit?

**Comment by lidavidm** [comment]
Up to you for CI: the current tests just check whether things build/byte-compile properly.

Idiomatic: all we ask is that the supplied bot generally matches the functionality of the Python3 starter bot (which is to just move randomly).
