### ISSUE TITLE
code in tutorial appears to be indented by single space

### ISSUE THREAD

**Issue by snaar** [HaliteChallenge/Halite-III#16]

**Comment by dhallstr** [comment]
![image](https://user-images.githubusercontent.com/31936156/47054914-e8ad9600-d171-11e8-9058-17d0a577555e.png)

**Comment by dhallstr** [comment]
Once I click on a line, the indentation for that line only is fixed

**Comment by whatelsie** [comment]
@dhallstr thanks for the screenshot & info. What version of Chrome are you running? Any extensions that might be interfering? I have not yet been able to reproduce the behavior on v68.0.

**Comment by snaar** [comment]
Looking around the internet seems like Grammarly is very intrusive: "It seems that Grammarly is injecting spans into the editor, wrapping any errors it finds, and this throws the editor into a state where the selection changes suddenly, and there doesn't appear to be a way to differentiate this from a normal selection." from https://github.com/facebook/draft-js/issues/616 for example. I'm going to say these issues belong to Grammarly.

**Comment by snaar** [comment]
I think the only pratical thing I can suggest is disabling it on our editor website: https://support.grammarly.com/hc/en-us/articles/115000091612-Disable-the-Grammarly-extension-on-one-or-more-websites
