### ISSUE TITLE
Early-terminating game with bad result

### ISSUE THREAD

**Issue by fohristiwhirl** [HaliteChallenge/Halite-III#178]
https://halite.io/play/?game_id=2973107

This game terminates early because 3 of the players are unable to take any action. However, the surviving player is not given 1st place (presumably because he has less halite). But this is unfair - he could well have won, if the game had proceeded to 500 turns.

**Comment by Janzert** [comment]
Testing shows that this broke with v1.1.6. My current guess is that PR #158 is the culprit.
