### ISSUE TITLE
additional colorblind theme

### ISSUE THREAD

**Issue by snaar** [HaliteChallenge/Halite-III#18]
Following up on discussion in Discord. We'd like to have a proposal from community on colors that work.

**Comment by whatelsie** [comment]
Thanks for these colors, @WillNess210! This has been started on the colorblind-theme branch, using a tint effect to prototype. I'll get proper assets generated tomorrow from my machine with the right design software. How does this look? Should we modify the yellow and white player names only for visibility on the stats panel?:

![colorblind](https://user-images.githubusercontent.com/3429409/47195315-6071f100-d329-11e8-8c72-6d496bc7ebfd.png)

**Comment by snaar** [comment]
It's out in the wild now as "Colorblind II".
