### ISSUE TITLE
Application bind address is always 127.0.0.1

### ISSUE THREAD

**Issue by divsurana** [HaliteChallenge/Halite-III#199]
The bind address when the application is deployed is always 127.0.0.1.
In this case, when you're trying to access the website from another machine in the cluster, it won't let you. In order to do that, the bind address should be 0.0.0.0.
What is the variable that takes care of this or the config file that would point me to the right direction?

**Comment by marvin-solano** [comment]
Please, use this:
bundle exec jekyll serve --host 0.0.0.0

The is
