### ISSUE TITLE
Local and online games play out differently

### ISSUE THREAD

**Issue by Kowys** [HaliteChallenge/Halite-III#34]
Two of my ships always collide immediately (upon spawning) when playing games online, leaving me with only 3 ships to start with every game. 

However, there was no such problem when I was running games locally. I always successfully resolve their movements without collision and start with 5 ships every time.

Please help look into this, thanks!

**Comment by lidavidm** [comment]
Hi Kowys, are you able to reproduce this using the same map seed and map size? (The online matches show what parameters were used to generate the map - you can provide these to the engine to play the same map locally)

**Comment by Kowys** [comment]
Thanks for the tip! I found that for 4 player games, I was able to replicate the early-game collisions locally. 

The results are still different for 2 player matches though, even though I ran both using the same map size+seed.

**Comment by lidavidm** [comment]
Just to make sure, is it that your bot behaves differently, or that the map itself is different?

If the bot behaves differently, I'd check for uses of `random`. Also, `game_map.naive_navigate` should help you avoid collisions in simple cases like these, if you aren't using it yet.

**Comment by Kowys** [comment]
So what I did was find a 2-player game my bot played online, copied over the map size and map seed, then ran that game again locally. You would think this would give the same result, but it doesn't. I thought I'd fixed the collision problem (using my own collision logic) but it only seems to work locally.

I don't think it's due to any random factors either. **All** of my bot's games online have produced that same initial collision between 2 ships, while it just doesn't happen when I run games locally (curiously, the collisions do happen for local 4-player games but not for 2-player ones).

**Comment by Kowys** [comment]
Well I just rewrote my collision detection algorithm, and I'm happy to say that my bot is now collision-free, both locally and online 👍 

I suspect that the discrepancy I encountered is a rare case stemming from an imperfect collision detection method I used previously. It shouldn't affect other users, I think, so I'm going to go ahead and close this issue.

**Comment by lidavidm** [comment]
Ah cool, glad you found the issue!
