### ISSUE TITLE
Problems with halite executable

### ISSUE THREAD

**Issue by AdamStelmaszczyk** [HaliteChallenge/Halite-III#35]
From https://github.com/HaliteChallenge/Halite-III/blob/master/starter_kits/C%2B%2B/README.md:

> Linux users: if you're having problems running the bundled halite executable, you will probably want to build your own from source. 

Where is the bundled halite executable?

I also tried to build `game_engine` (this will produce `halite`, right?) with:

```
cmake .
make
```

with gcc 7.3 and 8.1 on Ubuntu 16.04 compatible OS, but `make` fails with:

`ld: unrecognized option '--push-state--no-as-needed'`.

**Comment by lidavidm** [comment]
The [downloads on the website](https://halite.io/learn-programming-challenge/downloads) bundle the engine.

It seems the error is [because of Ubuntu](https://stackoverflow.com/questions/50024731/ld-unrecognized-option-push-state-no-as-needed). You can get around it by doing a release build:

```bash
cmake -DCMAKE_BUILD_TYPE=Release .
make
```

**Comment by AdamStelmaszczyk** [comment]
Excellent, thanks! I somehow missed that downloads website x|
