### ISSUE TITLE
ERROR: You must upload a .zip file.

### ISSUE THREAD

**Issue by mutantcows** [HaliteChallenge/Halite-III#68]
The drag and drop upload works fine, but when you use the file selection dialogue, it is validating for 
`file.type === "application/zip"` and browsers sometimes report zips as `application/x-zip-compressed`.

**Comment by mutantcows** [comment]
I submitted a pull request #69

**Comment by lidavidm** [comment]
This should now be deployed. Thanks for tracking this down!
