### ISSUE TITLE
naive_navigate shouldn't mark the cell as unsafe

### ISSUE THREAD

**Issue by ewanjones** [HaliteChallenge/Halite-III#70]
I can't comment for the other starter kits, but I don't think `naive_navigate` function should mark the cell unsafe (here)[https://github.com/HaliteChallenge/Halite-III/blob/ab9b43add935518734bd16f71e257048b2240ff6/starter_kits/Python3/hlt/game_map.py#L235]. For me, this is an unwanted side effect and I think the direction getting function could be split out.

Can I confirm that the bot compiles with the `hlt` module included in our projects? If this is the case I'll just change it there.

**Comment by snaar** [comment]
On the server side, there is no provided code. So yes, whatever you include in the zip file is what is going to get compiled and run, nothing more. So if you modify hlt - that works. The kits are designed to be modified by you, some people go as far as rewrite them from scratch.

**Comment by snaar** [comment]
So given that, we do want the starting kits to be suboptimal in respect to navigation, since they are merely a starting point.
