### ISSUE TITLE
Upgrade Lua to 5.3 and enable compilation

### ISSUE THREAD

**Issue by husmar** [HaliteChallenge/Halite-III#90]
Please upgrade the Lua interpreter to Lua 5.3 if possible and enable it in the compiler.py script by differentiating between LuaJIT and Lua 5.3 via an additional file extension, e.g. .lua53 or .luajit. 

LuaJIT implements most of Lua 5.2 already, Lua 5.3 is the current standard and has been released over three years ago.

**Comment by lidavidm** [comment]
Lua 5.3 should now be available. Submit a `MyBot.lua53`.
